/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.bdgenomics.services.reads;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RangeQuery implements org.apache.thrift.TBase<RangeQuery, RangeQuery._Fields>, java.io.Serializable, Cloneable, Comparable<RangeQuery> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RangeQuery");

  private static final org.apache.thrift.protocol.TField REFERENCE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("referenceName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField START_FIELD_DESC = new org.apache.thrift.protocol.TField("start", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField STOP_FIELD_DESC = new org.apache.thrift.protocol.TField("stop", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RangeQueryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RangeQueryTupleSchemeFactory());
  }

  public String referenceName; // required
  public long start; // required
  public long stop; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REFERENCE_NAME((short)1, "referenceName"),
    START((short)2, "start"),
    STOP((short)3, "stop");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REFERENCE_NAME
          return REFERENCE_NAME;
        case 2: // START
          return START;
        case 3: // STOP
          return STOP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __START_ISSET_ID = 0;
  private static final int __STOP_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REFERENCE_NAME, new org.apache.thrift.meta_data.FieldMetaData("referenceName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.START, new org.apache.thrift.meta_data.FieldMetaData("start", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STOP, new org.apache.thrift.meta_data.FieldMetaData("stop", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RangeQuery.class, metaDataMap);
  }

  public RangeQuery() {
  }

  public RangeQuery(
    String referenceName,
    long start,
    long stop)
  {
    this();
    this.referenceName = referenceName;
    this.start = start;
    setStartIsSet(true);
    this.stop = stop;
    setStopIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RangeQuery(RangeQuery other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetReferenceName()) {
      this.referenceName = other.referenceName;
    }
    this.start = other.start;
    this.stop = other.stop;
  }

  public RangeQuery deepCopy() {
    return new RangeQuery(this);
  }

  @Override
  public void clear() {
    this.referenceName = null;
    setStartIsSet(false);
    this.start = 0;
    setStopIsSet(false);
    this.stop = 0;
  }

  public String getReferenceName() {
    return this.referenceName;
  }

  public RangeQuery setReferenceName(String referenceName) {
    this.referenceName = referenceName;
    return this;
  }

  public void unsetReferenceName() {
    this.referenceName = null;
  }

  /** Returns true if field referenceName is set (has been assigned a value) and false otherwise */
  public boolean isSetReferenceName() {
    return this.referenceName != null;
  }

  public void setReferenceNameIsSet(boolean value) {
    if (!value) {
      this.referenceName = null;
    }
  }

  public long getStart() {
    return this.start;
  }

  public RangeQuery setStart(long start) {
    this.start = start;
    setStartIsSet(true);
    return this;
  }

  public void unsetStart() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __START_ISSET_ID);
  }

  /** Returns true if field start is set (has been assigned a value) and false otherwise */
  public boolean isSetStart() {
    return EncodingUtils.testBit(__isset_bitfield, __START_ISSET_ID);
  }

  public void setStartIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __START_ISSET_ID, value);
  }

  public long getStop() {
    return this.stop;
  }

  public RangeQuery setStop(long stop) {
    this.stop = stop;
    setStopIsSet(true);
    return this;
  }

  public void unsetStop() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STOP_ISSET_ID);
  }

  /** Returns true if field stop is set (has been assigned a value) and false otherwise */
  public boolean isSetStop() {
    return EncodingUtils.testBit(__isset_bitfield, __STOP_ISSET_ID);
  }

  public void setStopIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STOP_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REFERENCE_NAME:
      if (value == null) {
        unsetReferenceName();
      } else {
        setReferenceName((String)value);
      }
      break;

    case START:
      if (value == null) {
        unsetStart();
      } else {
        setStart((Long)value);
      }
      break;

    case STOP:
      if (value == null) {
        unsetStop();
      } else {
        setStop((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REFERENCE_NAME:
      return getReferenceName();

    case START:
      return Long.valueOf(getStart());

    case STOP:
      return Long.valueOf(getStop());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REFERENCE_NAME:
      return isSetReferenceName();
    case START:
      return isSetStart();
    case STOP:
      return isSetStop();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RangeQuery)
      return this.equals((RangeQuery)that);
    return false;
  }

  public boolean equals(RangeQuery that) {
    if (that == null)
      return false;

    boolean this_present_referenceName = true && this.isSetReferenceName();
    boolean that_present_referenceName = true && that.isSetReferenceName();
    if (this_present_referenceName || that_present_referenceName) {
      if (!(this_present_referenceName && that_present_referenceName))
        return false;
      if (!this.referenceName.equals(that.referenceName))
        return false;
    }

    boolean this_present_start = true;
    boolean that_present_start = true;
    if (this_present_start || that_present_start) {
      if (!(this_present_start && that_present_start))
        return false;
      if (this.start != that.start)
        return false;
    }

    boolean this_present_stop = true;
    boolean that_present_stop = true;
    if (this_present_stop || that_present_stop) {
      if (!(this_present_stop && that_present_stop))
        return false;
      if (this.stop != that.stop)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(RangeQuery other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReferenceName()).compareTo(other.isSetReferenceName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReferenceName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.referenceName, other.referenceName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStart()).compareTo(other.isSetStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.start, other.start);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStop()).compareTo(other.isSetStop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStop()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stop, other.stop);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RangeQuery(");
    boolean first = true;

    sb.append("referenceName:");
    if (this.referenceName == null) {
      sb.append("null");
    } else {
      sb.append(this.referenceName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("start:");
    sb.append(this.start);
    first = false;
    if (!first) sb.append(", ");
    sb.append("stop:");
    sb.append(this.stop);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (referenceName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'referenceName' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'start' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'stop' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RangeQueryStandardSchemeFactory implements SchemeFactory {
    public RangeQueryStandardScheme getScheme() {
      return new RangeQueryStandardScheme();
    }
  }

  private static class RangeQueryStandardScheme extends StandardScheme<RangeQuery> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RangeQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REFERENCE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.referenceName = iprot.readString();
              struct.setReferenceNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // START
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.start = iprot.readI64();
              struct.setStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STOP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.stop = iprot.readI64();
              struct.setStopIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetStart()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'start' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStop()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'stop' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RangeQuery struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.referenceName != null) {
        oprot.writeFieldBegin(REFERENCE_NAME_FIELD_DESC);
        oprot.writeString(struct.referenceName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(START_FIELD_DESC);
      oprot.writeI64(struct.start);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STOP_FIELD_DESC);
      oprot.writeI64(struct.stop);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RangeQueryTupleSchemeFactory implements SchemeFactory {
    public RangeQueryTupleScheme getScheme() {
      return new RangeQueryTupleScheme();
    }
  }

  private static class RangeQueryTupleScheme extends TupleScheme<RangeQuery> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RangeQuery struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.referenceName);
      oprot.writeI64(struct.start);
      oprot.writeI64(struct.stop);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RangeQuery struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.referenceName = iprot.readString();
      struct.setReferenceNameIsSet(true);
      struct.start = iprot.readI64();
      struct.setStartIsSet(true);
      struct.stop = iprot.readI64();
      struct.setStopIsSet(true);
    }
  }

}

